modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "guymisstep"
version = "${version}"
displayName = "GuyMisstep"
authors = "Kall"
description = '''
A Minecraft mod
'''
#logoFile = ""

[[mixins]]
config = "guymisstep.mixins.json"
